module.exports = {
    254: [ "New Subfile Type", "NewSubfileType" ],
    255: [ "Subfile Type", "SubfileType" ],
    256: [ "Image width", "ImageWidth" ],
    257: [ "Image height", "ImageLength" ],
    258: [ "Number of bits per component", "BitsPerSample" ],
    259: [ "Compression scheme", "Compression", {
        1: "uncompressed",
        2: "CCITT 1D",
        3: "Group 3 Fax",
        4: "Group 4 Fax",
        5: "LZW",
        6: "JPEG compression",
        7: "JPEG ('new-style' JPEG)",
        8: "Deflate ('Adobe-style')",
        32773: "PackBits"
    } ],
    262: [ "Pixel composition", "PhotmetricInerpretation", {
        0: "WhiteIsZero",
        1: "BlackIsZero",
        2: "RGB",
        3: "RGB Palette",
        4: "Transparency mask",
        5: "CMYK",
        6: "YCbCr",
        8: "CIELab"
    } ],
    263: [ "Threshholding", "Threshholding" ],
    264: [ "Cell Width", "CellWidth" ],
    265: [ "Cell Length", "CellLength" ],
    266: [ "Fill Order", "FillOrder" ],
    269: [ "Document Name", "DocumentName" ],
    270: [ "Image title", "ImageDescription" ],
    271: [ "Make", "Make" ],
    272: [ "Model", "Model" ],
    273: [ "Image data location", "StripOffsets" ],
    274: [ "Orientation of image", "Orientation", {
        1: "Normal",
        2: "Reverse?",
        3: "Upside-down",
        4: "Upside-down Reverse",
        5: "90 degree CW",
        6: "90 degree CW reverse",
        7: "90 degree CCW",
        8: "90 degree CCW reverse"
    } ],
    277: [ "Number of components", "SamplesPerPixel" ],
    278: [ "Number of rows per strip", "RowsPerStrip" ],
    279: [ "Bytes per compressed strip", "StripByteCounts" ],
    280: [ "Min Sample Value", "MinSampleValue" ],
    281: [ "Max Sample Value", "MaxSampleValue" ],
    282: [ "X Resolution", "XResolution" ],
    283: [ "Y Resolution", "YResolution" ],
    285: [ "Page Name", "PageName" ],
    286: [ "X Position", "XPosition" ],
    287: [ "Y Position", "YPosition" ],
    288: [ "Free Offsets", "FreeOffsets" ],
    289: [ "Free Byte Counts", "FreeByteCounts" ],
    290: [ "Gray Response Unit", "GrayResponseUnit" ],
    291: [ "Gray Response Curve", "GrayResponseCurve" ],
    292: [ "T4 Options", "T4Options" ],
    293: [ "T6 Options", "T6Options" ],
    296: [ "Resolution Unit", "ResolutionUnit", {
        2: "inches",
        3: "centimeters"
    } ],
    297: [ "Page Number", "PageNumber" ],
    301: [ "Transfer function", "TransferFunction" ],
    306: [ "Date and time", "DateTime" ],
    316: [ "Host Computer", "HostComputer" ],
    317: [ "Predictor", "Predictor" ],
    318: [ "White point chromaticity", "WhitePoint" ],
    319: [ "Chromaticities of primaries", "PrimaryChromaticities" ],
    320: [ "Color Map", "ColorMap" ],
    321: [ "Halftone Hints", "HalftoneHints" ],
    322: [ "Tile Width", "TileWidth" ],
    323: [ "Tile Length", "TileLength" ],
    324: [ "Tile Offsets", "TileOffsets" ],
    325: [ "Tile Byte Counts", "TileByteCounts" ],
    330: [ "Offset to child IFDs", "SubIFDs" ],
    332: [ "Ink Set", "InkSet" ],
    333: [ "Ink Names", "InkNames" ],
    334: [ "Number Of Inks", "NumberOfInks" ],
    336: [ "Dot Range", "DotRange" ],
    337: [ "Target Printer", "TargetPrinter" ],
    338: [ "Extra Samples", "ExtraSamples" ],
    339: [ "Sample Format", "SampleFormat" ],
    340: [ "S Min Sample Value", "SMinSampleValue" ],
    341: [ "S MaxSample Value", "SMaxSampleValue" ],
    342: [ "Transfer Range", "TransferRange" ],
    512: [ "JPEG Proc", "JPEGProc" ],
    513: [ "Offset to JPEG SOI", "JPEGInterchangeFormat" ],
    514: [ "Bytes of JPEG Data", "JPEGInterchangeFormatLength" ],
    517: [ "JPEG Lossless Predictors", "JPEGLosslessPredictors" ],
    518: [ "JPEG Point Transforms", "JPEGPointTransforms" ],
    519: [ "JPEG Q Tables", "JPEGQTables" ],
    520: [ "JPEG DC Tables", "JPEGDCTables" ],
    521: [ "JPEG AC Tables", "JPEGACTables" ],
    529: [ "Color space transformation matrix coefficients", "YCbCrCoefficients" ],
    530: [ "Subsampling ratio of Y to C", "YCbCrSubSampling" ],
    531: [ "Y and C positioning", "YCbCrPositioning", {
        1: "centered",
        2: "co-sited"
    } ],
    532: [ "Pair of black and white reference values", "ReferenceBlackWhite" ],
    33421: [ "CFA Repeat Pattern Dim", "CFARepeatPatternDim" ],
    33422: [ "CFA Pattern", "CFAPattern" ],
    34665: [ "Exif tag", "ExifIfdPointer" ],
    34853: [ "GPS tag", "GPSInfoIfdPointer" ],
    34885: [ "ISO Speed Rating", "ISOSpeedRating" ],
    37393: [ "Number assigned to an image", "ImageNumber" ],
    50648: [ "Canon RAW IFD Specific Tag", "CanonRawIfdTag" ],
    50752: [ "Canon RAW IFD slices", "CanonRawIfdSlices" ],
    50706: [ "DNG Version", "DNGVersion" ],
    50707: [ "DNG Backward Version", "DNGBackwardVersion" ],
    50708: [ "Unique Camera Model", "UniqueCameraModel" ],
    50709: [ "Localized Camera Model", "LocalizedCameraModel" ],
    50710: [ "CFA Plane Color", "CFAPlaneColor" ],
    50711: [ "CFA Layout", "CFALayout" ],
    50712: [ "Linearization Table", "LinearizationTable" ],
    50713: [ "Black Level Repeat Dim", "BlackLevelRepeatDim" ],
    50714: [ "Black Level", "BlackLevel" ],
    50715: [ "Black Level Delta H", "BlackLevelDeltaH" ],
    50716: [ "Black Level Delta V", "BlackLevelDeltaV" ],
    50717: [ "White Level", "WhiteLevel" ],
    50718: [ "Default Scale", "DefaultScale" ],
    50719: [ "Default Crop Origin", "DefaultCropOrigin" ],
    50720: [ "Default Crop Size", "DefaultCropSize" ],
    50778: [ "Calibration Illuminant 1", "CalibrationIlluminant1" ],
    50779: [ "Calibration Illuminant 2", "CalibrationIlluminant2" ],
    50721: [ "Color Matrix 1", "ColorMatrix1" ],
    50722: [ "Color Matrix 2", "ColorMatrix2" ],
    50723: [ "Camera Calibration 1", "CameraCalibration1" ],
    50724: [ "Camera Calibration 2", "CameraCalibration2" ],
    50725: [ "Reduction Matrix 1", "ReductionMatrix1" ],
    50726: [ "Reduction Matrix 2", "ReductionMatrix2" ],
    50727: [ "Analog Balance", "AnalogBalance" ],
    50728: [ "As Shot Neutral", "AsShotNeutral" ],
    50729: [ "As Shot White XY", "AsShotWhiteXY" ],
    50730: [ "Baseline Exposure", "BaselineExposure" ],
    50731: [ "Baseline Noise", "BaselineNoise" ],
    50732: [ "Baseline Sharpness", "BaselineSharpness" ],
    50734: [ "Linear Response Limit", "LinearResponseLimit" ],
    50735: [ "Camera Serial Number", "CameraSerialNumber" ],
    50736: [ "Lens Info", "LensInfo" ],
    50737: [ "Chroma Blur Radius", "ChromaBlurRadius" ],
    50739: [ "Shadow Scale", "ShadowScale" ],
    50741: [ "Maker Note Safety", "MakerNoteSafety" ],
    50781: [ "Raw Data Unique ID", "RawDataUniqueID" ],
    50827: [ "Original Raw File Name", "OriginalRawFileName" ],
    50828: [ "Original Raw File Data", "OriginalRawFileData" ],
    50829: [ "Active Area", "ActiveArea" ],
    50830: [ "Masked Areas", "MaskedAreas" ],
    50831: [ "As Shot ICC Profile", "AsShotICCProfile" ],
    50832: [ "As Shot Pre Profile Matrix", "AsShotPreProfileMatrix" ],
    50833: [ "Current ICC Profile", "CurrentICCProfile" ],
    50834: [ "Current Pre Profile Matrix", "CurrentPreProfileMatrix" ],
    50879: [ "Colorimetric Reference", "ColorimetricReference" ],
    50931: [ "Camera Calibration Signature", "CameraCalibrationSignature" ],
    50932: [ "Profile Calibration Signature", "ProfileCalibrationSignature" ],
    50933: [ "Extra Camera Profiles", "ExtraCameraProfiles" ],
    50934: [ "As Shot Profile Name", "AsShotProfileName" ],
    50935: [ "Noise Reduction Applied", "NoiseReductionApplied" ],
    50936: [ "Profile Name", "ProfileName" ],
    50941: [ "Profile Embed Policy", "ProfileEmbedPolicy" ],
    50942: [ "Profile Copyright", "ProfileCopyright" ],
    50964: [ "Forward Matrix 1", "ForwardMatrix1" ],
    50965: [ "Forward Matrix 2", "ForwardMatrix2" ],
    50966: [ "Preview Application Name", "PreviewApplicationName" ],
    50967: [ "Preview Application Version", "PreviewApplicationVersion" ],
    50968: [ "Preview Settings Name", "PreviewSettingsName" ],
    50969: [ "Preview Settings Digest", "PreviewSettingsDigest" ],
    50970: [ "Preview Color Space", "PreviewColorSpace" ],
    50971: [ "Preview Date Time", "PreviewDateTime" ],
    50972: [ "Raw Image Digest", "RawImageDigest" ],
    50973: [ "Original Raw File Digest", "OriginalRawFileDigest" ],
    50974: [ "Sub Tile Block Size", "SubTileBlockSize" ],
    50975: [ "Row Interleave Factor", "RowInterleaveFactor" ],
    51008: [ "OpcodeList1", "OpcodeList1" ],
    51009: [ "OpcodeList2", "OpcodeList2" ],
    51022: [ "OpcodeList3", "OpcodeList3" ],
    51041: [ "NoiseProfile", "NoiseProfile" ],
    33434: [ "Exposure time, given in seconds.", "ExposureTime" ],
    33437: [ "The F number.", "FNumber" ],
    34850: [ "The class of the program used by the camera to set exposure when the picture is taken.", "ExposureProgram", {
        0: "Not defined",
        1: "Manual",
        2: "Normal program",
        3: "Aperture priority",
        4: "Shutter priority",
        5: "Creative program",
        6: "Action program",
        7: "Portrait mode",
        8: "Landscape mode"
    } ],
    34852: [ "Indicates the spectral sensitivity of each channel of the camera used.", "SpectralSensitivity" ],
    34855: [ "Indicates the ISO Speed and ISO Latitude of the camera or input device as specified in ISO 12232.", "ISOSpeedRatings" ],
    34856: [ "Indicates the Opto-Electric Conversion Function (OECF) specified in ISO 14524.", "OECF" ],
    36864: [ "The version of the supported Exif standard.", "ExifVersion" ],
    36867: [ "The date and time when the original image data was generated.", "DateTimeOriginal" ],
    37121: [ "Specific to compressed data; specifies the channels and complements PhotometricInterpretation", "ComponentsConfiguration" ],
    37122: [ "Specific to compressed data; states the compressed bits per pixel.", "CompressedBitsPerPixel" ],
    37377: [ "Shutter speed.", "ShutterSpeedValue" ],
    37378: [ "The lens aperture.", "ApertureValue" ],
    37379: [ "The value of brightness.", "BrightnessValue" ],
    37382: [ "The distance to the subject, given in meters.", "SubjectDistance" ],
    37384: [ "The kind of light source.", "LightSource" ],
    37385: [ "Indicates the status of flash when the image was shot.", "Flash", {
        0: "Flash did not fire",
        1: "Flash fired",
        5: "Strobe return light not detected",
        7: "Strobe return light detected",
        8: "On, Did not fired",
        9: "Flash fired, compulsory flash mode",
        13: "Flash fired, compulsory flash mode, return light not detected",
        15: "Flash fired, compulsory flash mode, return light detected",
        16: "Flash did not fire, compulsory flash mode",
        24: "Flash did not fire, auto mode",
        25: "Flash fired, auto mode",
        29: "Flash fired, auto mode, return light not detected",
        31: "Flash fired, auto mode, return light detected",
        32: "No flash function",
        65: "Flash fired, red-eye reduction mode",
        69: "Flash fired, red-eye reduction mode, return light not detected",
        71: "Flash fired, red-eye reduction mode, return light detected",
        73: "Flash fired, compulsory flash mode, red-eye reduction mode",
        77: "Flash fired, compulsory flash mode, red-eye reduction mode, return light not detected",
        79: "Flash fired, compulsory flash mode, red-eye reduction mode, return light detected",
        89: "Flash fired, auto mode, red-eye reduction mode",
        93: "Flash fired, auto mode, return light not detected, red-eye reduction mode",
        95: "Flash fired, auto mode, return light detected, red-eye reduction mode"
    } ],
    37386: [ "The actual focal length of the lens, in mm.", "FocalLength" ],
    37396: [ "Indicates the location and area of the main subject in the overall scene.", "SubjectArea" ],
    37500: [ "Manufacturer specific information.", "MakerNote" ],
    37520: [ "A tag used to record fractions of seconds for the DateTime tag.", "SubsecTime" ],
    37521: [ "A tag used to record fractions of seconds for the DateTimeOriginal tag.", "SubsecTimeOriginal" ],
    40961: [ "The color space information tag is always recorded as the color space specifier.", "ColorSpace" ],
    40962: [ "Specific to compressed data; the valid width of the meaningful image.", "PixelXDimension" ],
    40963: [ "Specific to compressed data; the valid height of the meaningful image.", "PixelYDimension" ],
    40964: [ "Used to record the name of an audio file related to the image data.", "RelatedSoundFile" ],
    41483: [ "Indicates the strobe energy at the time the image is captured, as measured in Beam Candle Power Seconds", "FlashEnergy" ],
    41484: [ "Records the camera or input device spatial frequency table and SFR values in the direction of image width, image height, and diagonal direction, as specified in ISO 12233.", "SpatialFrequencyResponse" ],
    41486: [ "Indicates the number of pixels in the image width (X) direction per FocalPlaneResolutionUnit on the camera focal plane.", "FocalPlaneXResolution" ],
    41487: [ "Indicates the number of pixels in the image height (Y) direction per FocalPlaneResolutionUnit on the camera focal plane.", "FocalPlaneYResolution" ],
    41488: [ "Indicates the unit for measuring FocalPlaneXResolution and FocalPlaneYResolution.", "FocalPlaneResolutionUnit" ],
    41492: [ "Indicates the location of the main subject in the scene.", "SubjectLocation" ],
    41493: [ "Indicates the exposure index selected on the camera or input device at the time the image is captured.", "ExposureIndex" ],
    41495: [ "Indicates the image sensor type on the camera or input device.", "SensingMethod" ],
    41728: [ "Indicates the image source.", "FileSource" ],
    41729: [ "Indicates the type of scene.", "SceneType" ],
    41730: [ "Indicates the color filter array (CFA) geometric pattern of the image sensor when a one-chip color area sensor is used.", "CFAPattern" ],
    41986: [ "Indicates the exposure mode set when the image was shot.", "ExposureMode", {
        0: "Auto exposure",
        1: "Manual exposure",
        2: "Auto bracket"
    } ],
    41987: [ "Indicates the white balance mode set when the image was shot.", "WhiteBalance" ],
    41989: [ "Indicates the equivalent focal length assuming a 35mm film camera, in mm.", "FocalLengthIn35mmFilm" ],
    41992: [ "Indicates the direction of contrast processing applied by the camera when the image was shot.", "Contrast" ],
    41993: [ "Indicates the direction of saturation processing applied by the camera when the image was shot.", "Saturation" ],
    41994: [ "Indicates the direction of sharpness processing applied by the camera when the image was shot.", "Sharpness" ],
    41995: [ "This tag indicates information on the picture-taking conditions of a particular camera model.", "DeviceSettingDescription" ],
    42016: [ "Indicates an identifier assigned uniquely to each image.", "ImageUniqueID" ]
}
